"""Add helpdesk tables

Revision ID: 0b8fda1c481a
Revises: cb1a84e871ea
Create Date: 2026-07-11 15:15:56.466055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8fda1c481a'
down_revision: Union[str, Sequence[str], None] = 'cb1a84e871ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_tickets',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpdesk_tickets_employee_id'), 'helpdesk_tickets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_helpdesk_tickets_id'), 'helpdesk_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_helpdesk_tickets_tenant_id'), 'helpdesk_tickets', ['tenant_id'], unique=False)
    op.create_table('helpdesk_comments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpdesk_comments_author_id'), 'helpdesk_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_helpdesk_comments_id'), 'helpdesk_comments', ['id'], unique=False)
    op.create_index(op.f('ix_helpdesk_comments_tenant_id'), 'helpdesk_comments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_helpdesk_comments_ticket_id'), 'helpdesk_comments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_helpdesk_comments_ticket_id'), table_name='helpdesk_comments')
    op.drop_index(op.f('ix_helpdesk_comments_tenant_id'), table_name='helpdesk_comments')
    op.drop_index(op.f('ix_helpdesk_comments_id'), table_name='helpdesk_comments')
    op.drop_index(op.f('ix_helpdesk_comments_author_id'), table_name='helpdesk_comments')
    op.drop_table('helpdesk_comments')
    op.drop_index(op.f('ix_helpdesk_tickets_tenant_id'), table_name='helpdesk_tickets')
    op.drop_index(op.f('ix_helpdesk_tickets_id'), table_name='helpdesk_tickets')
    op.drop_index(op.f('ix_helpdesk_tickets_employee_id'), table_name='helpdesk_tickets')
    op.drop_table('helpdesk_tickets')
    # ### end Alembic commands ###
