"""add_onboarding_and_approvals

Revision ID: 2161e5ea2231
Revises: b0d37692f9a7
Create Date: 2026-07-09 16:28:52.731077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2161e5ea2231'
down_revision: Union[str, Sequence[str], None] = 'b0d37692f9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_range', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('onboardings',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboardings_employee_id'), 'onboardings', ['employee_id'], unique=True)
    op.create_index(op.f('ix_onboardings_id'), 'onboardings', ['id'], unique=False)
    op.create_index(op.f('ix_onboardings_tenant_id'), 'onboardings', ['tenant_id'], unique=False)
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False))
    op.add_column('employees', sa.Column('father_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('mother_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('aadhaar_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('driving_license_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'driving_license_number')
    op.drop_column('employees', 'passport_number')
    op.drop_column('employees', 'aadhaar_number')
    op.drop_column('employees', 'pan_number')
    op.drop_column('employees', 'mother_name')
    op.drop_column('employees', 'father_name')
    op.drop_column('documents', 'status')
    op.drop_index(op.f('ix_onboardings_tenant_id'), table_name='onboardings')
    op.drop_index(op.f('ix_onboardings_id'), table_name='onboardings')
    op.drop_index(op.f('ix_onboardings_employee_id'), table_name='onboardings')
    op.drop_table('onboardings')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
