"""add_lop_and_sandwich_to_leave

Revision ID: 463afa9ad6a0
Revises: b18dcee73e5b
Create Date: 2026-07-10 16:42:03.149608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463afa9ad6a0'
down_revision: Union[str, Sequence[str], None] = 'b18dcee73e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_applications', sa.Column('lop_days', sa.Float(), nullable=False))
    op.add_column('leave_applications', sa.Column('is_sandwich', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_applications', 'is_sandwich')
    op.drop_column('leave_applications', 'lop_days')
    # ### end Alembic commands ###
