"""extend_recruitment_schema_v2

Revision ID: 619c5446685a
Revises: 97556a406034
Create Date: 2026-07-10 18:07:50.309551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619c5446685a'
down_revision: Union[str, Sequence[str], None] = '97556a406034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_references',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('reference_name', sa.String(), nullable=False),
    sa.Column('reference_company', sa.String(), nullable=True),
    sa.Column('reference_designation', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('reference_email', sa.String(), nullable=True),
    sa.Column('reference_phone', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_references_candidate_id'), 'candidate_references', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_references_id'), 'candidate_references', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_references_tenant_id'), 'candidate_references', ['tenant_id'], unique=False)
    op.create_table('recruitment_pipeline',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=False),
    sa.Column('moved_by', sa.String(), nullable=True),
    sa.Column('move_reason', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitment_pipeline_candidate_id'), 'recruitment_pipeline', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruitment_pipeline_id'), 'recruitment_pipeline', ['id'], unique=False)
    op.create_index(op.f('ix_recruitment_pipeline_tenant_id'), 'recruitment_pipeline', ['tenant_id'], unique=False)
    op.create_table('recruiter_assignments',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_assignments_id'), 'recruiter_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_assignments_requisition_id'), 'recruiter_assignments', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_recruiter_assignments_tenant_id'), 'recruiter_assignments', ['tenant_id'], unique=False)
    op.create_table('reference_checks',
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reference_id'], ['candidate_references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_checks_id'), 'reference_checks', ['id'], unique=False)
    op.create_index(op.f('ix_reference_checks_reference_id'), 'reference_checks', ['reference_id'], unique=False)
    op.create_index(op.f('ix_reference_checks_tenant_id'), 'reference_checks', ['tenant_id'], unique=False)
    op.add_column('assessments', sa.Column('assessment_type', sa.String(), server_default='aptitude', nullable=False))
    op.add_column('assessments', sa.Column('max_score', sa.Integer(), server_default='100', nullable=False))
    op.add_column('background_verification', sa.Column('address_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('background_verification', sa.Column('initiated_at', sa.DateTime(), nullable=True))
    op.add_column('background_verification', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('background_verification', sa.Column('vendor_name', sa.String(), nullable=True))
    op.alter_column('candidate_experience', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('candidates', sa.Column('address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('source', sa.String(), server_default='career_portal', nullable=False))
    op.add_column('candidates', sa.Column('application_source', sa.String(), nullable=True))
    op.alter_column('candidates', 'resume_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('hiring_plans', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('hiring_plans', sa.Column('team', sa.String(), nullable=True))
    op.add_column('hiring_plans', sa.Column('hiring_timeline', sa.String(), nullable=True))
    op.add_column('hiring_plans', sa.Column('business_justification', sa.Text(), nullable=True))
    op.alter_column('interview_feedback', 'comments',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('interviews', sa.Column('timezone', sa.String(), server_default='Asia/Kolkata', nullable=False))
    op.add_column('interviews', sa.Column('rescheduled_at', sa.DateTime(), nullable=True))
    op.add_column('interviews', sa.Column('rescheduled_reason', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('qualifications', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_range', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('application_deadline', sa.Date(), nullable=True))
    op.alter_column('job_postings', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('job_requisitions', sa.Column('job_type', sa.String(), nullable=True))
    op.add_column('job_requisitions', sa.Column('expected_joining_date', sa.Date(), nullable=True))
    op.add_column('offers', sa.Column('employment_type', sa.String(), server_default='full_time', nullable=False))
    op.add_column('offers', sa.Column('department_name', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('reporting_manager', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('joining_bonus', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('offers', sa.Column('probation_period', sa.Integer(), server_default='90', nullable=False))
    op.add_column('offers', sa.Column('offer_expiry_date', sa.DateTime(), nullable=True))
    op.alter_column('recruitment_timelines', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recruitment_timelines', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('offers', 'offer_expiry_date')
    op.drop_column('offers', 'probation_period')
    op.drop_column('offers', 'joining_bonus')
    op.drop_column('offers', 'reporting_manager')
    op.drop_column('offers', 'department_name')
    op.drop_column('offers', 'employment_type')
    op.drop_column('job_requisitions', 'expected_joining_date')
    op.drop_column('job_requisitions', 'job_type')
    op.alter_column('job_postings', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('job_postings', 'application_deadline')
    op.drop_column('job_postings', 'salary_range')
    op.drop_column('job_postings', 'benefits')
    op.drop_column('job_postings', 'responsibilities')
    op.drop_column('job_postings', 'qualifications')
    op.drop_column('interviews', 'rescheduled_reason')
    op.drop_column('interviews', 'rescheduled_at')
    op.drop_column('interviews', 'timezone')
    op.alter_column('interview_feedback', 'comments',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('hiring_plans', 'business_justification')
    op.drop_column('hiring_plans', 'hiring_timeline')
    op.drop_column('hiring_plans', 'team')
    op.drop_column('hiring_plans', 'branch')
    op.alter_column('candidates', 'resume_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('candidates', 'application_source')
    op.drop_column('candidates', 'source')
    op.drop_column('candidates', 'github_url')
    op.drop_column('candidates', 'linkedin_url')
    op.drop_column('candidates', 'portfolio_url')
    op.drop_column('candidates', 'address')
    op.alter_column('candidate_experience', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('background_verification', 'vendor_name')
    op.drop_column('background_verification', 'completed_at')
    op.drop_column('background_verification', 'initiated_at')
    op.drop_column('background_verification', 'address_status')
    op.drop_column('assessments', 'max_score')
    op.drop_column('assessments', 'assessment_type')
    op.drop_index(op.f('ix_reference_checks_tenant_id'), table_name='reference_checks')
    op.drop_index(op.f('ix_reference_checks_reference_id'), table_name='reference_checks')
    op.drop_index(op.f('ix_reference_checks_id'), table_name='reference_checks')
    op.drop_table('reference_checks')
    op.drop_index(op.f('ix_recruiter_assignments_tenant_id'), table_name='recruiter_assignments')
    op.drop_index(op.f('ix_recruiter_assignments_requisition_id'), table_name='recruiter_assignments')
    op.drop_index(op.f('ix_recruiter_assignments_id'), table_name='recruiter_assignments')
    op.drop_table('recruiter_assignments')
    op.drop_index(op.f('ix_recruitment_pipeline_tenant_id'), table_name='recruitment_pipeline')
    op.drop_index(op.f('ix_recruitment_pipeline_id'), table_name='recruitment_pipeline')
    op.drop_index(op.f('ix_recruitment_pipeline_candidate_id'), table_name='recruitment_pipeline')
    op.drop_table('recruitment_pipeline')
    op.drop_index(op.f('ix_candidate_references_tenant_id'), table_name='candidate_references')
    op.drop_index(op.f('ix_candidate_references_id'), table_name='candidate_references')
    op.drop_index(op.f('ix_candidate_references_candidate_id'), table_name='candidate_references')
    op.drop_table('candidate_references')
    # ### end Alembic commands ###
