"""add_finance_modules

Revision ID: 71bb7839308a
Revises: e8d7f767e098
Create Date: 2026-07-16 14:05:42.410318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bb7839308a'
down_revision: Union[str, Sequence[str], None] = 'e8d7f767e098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_accounts',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_accounts_code'), 'finance_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_finance_accounts_id'), 'finance_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_finance_accounts_tenant_id'), 'finance_accounts', ['tenant_id'], unique=False)
    op.create_table('finance_budget_forecasts',
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('forecast_revenue', sa.Float(), nullable=False),
    sa.Column('forecast_expense', sa.Float(), nullable=False),
    sa.Column('ai_suggestions', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_budget_forecasts_id'), 'finance_budget_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_finance_budget_forecasts_tenant_id'), 'finance_budget_forecasts', ['tenant_id'], unique=False)
    op.create_table('finance_budgets',
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_budgets_id'), 'finance_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_finance_budgets_tenant_id'), 'finance_budgets', ['tenant_id'], unique=False)
    op.create_table('finance_expense_policies',
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('max_limit', sa.Float(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_expense_policies_id'), 'finance_expense_policies', ['id'], unique=False)
    op.create_index(op.f('ix_finance_expense_policies_tenant_id'), 'finance_expense_policies', ['tenant_id'], unique=False)
    op.create_table('finance_invoices',
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('balance_due', sa.Float(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_invoices_id'), 'finance_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_finance_invoices_invoice_number'), 'finance_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_finance_invoices_tenant_id'), 'finance_invoices', ['tenant_id'], unique=False)
    op.create_table('finance_journal_entries',
    sa.Column('entry_number', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('reversed_entry_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_journal_entries_entry_number'), 'finance_journal_entries', ['entry_number'], unique=True)
    op.create_index(op.f('ix_finance_journal_entries_id'), 'finance_journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_tenant_id'), 'finance_journal_entries', ['tenant_id'], unique=False)
    op.create_table('finance_tax_filings',
    sa.Column('tax_type', sa.String(), nullable=False),
    sa.Column('filing_period', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('return_form', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_tax_filings_id'), 'finance_tax_filings', ['id'], unique=False)
    op.create_index(op.f('ix_finance_tax_filings_tenant_id'), 'finance_tax_filings', ['tenant_id'], unique=False)
    op.create_table('finance_budget_variances',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('actual_spend', sa.Float(), nullable=False),
    sa.Column('budget_spend', sa.Float(), nullable=False),
    sa.Column('variance_amount', sa.Float(), nullable=False),
    sa.Column('variance_pct', sa.Float(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['finance_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_budget_variances_id'), 'finance_budget_variances', ['id'], unique=False)
    op.create_index(op.f('ix_finance_budget_variances_tenant_id'), 'finance_budget_variances', ['tenant_id'], unique=False)
    op.create_table('finance_expense_claims',
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_expense_claims_claim_number'), 'finance_expense_claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_finance_expense_claims_id'), 'finance_expense_claims', ['id'], unique=False)
    op.create_index(op.f('ix_finance_expense_claims_tenant_id'), 'finance_expense_claims', ['tenant_id'], unique=False)
    op.create_table('finance_invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_invoice_items_id'), 'finance_invoice_items', ['id'], unique=False)
    op.create_table('finance_invoice_payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_invoice_payments_id'), 'finance_invoice_payments', ['id'], unique=False)
    op.create_table('finance_journal_items',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('partner_type', sa.String(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['finance_journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_journal_items_id'), 'finance_journal_items', ['id'], unique=False)
    op.create_table('finance_tax_transactions',
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('reference_model', sa.String(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_tax_transactions_id'), 'finance_tax_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_finance_tax_transactions_tenant_id'), 'finance_tax_transactions', ['tenant_id'], unique=False)
    op.create_table('finance_expense_lines',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['finance_expense_claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_expense_lines_id'), 'finance_expense_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_expense_lines_id'), table_name='finance_expense_lines')
    op.drop_table('finance_expense_lines')
    op.drop_index(op.f('ix_finance_tax_transactions_tenant_id'), table_name='finance_tax_transactions')
    op.drop_index(op.f('ix_finance_tax_transactions_id'), table_name='finance_tax_transactions')
    op.drop_table('finance_tax_transactions')
    op.drop_index(op.f('ix_finance_journal_items_id'), table_name='finance_journal_items')
    op.drop_table('finance_journal_items')
    op.drop_index(op.f('ix_finance_invoice_payments_id'), table_name='finance_invoice_payments')
    op.drop_table('finance_invoice_payments')
    op.drop_index(op.f('ix_finance_invoice_items_id'), table_name='finance_invoice_items')
    op.drop_table('finance_invoice_items')
    op.drop_index(op.f('ix_finance_expense_claims_tenant_id'), table_name='finance_expense_claims')
    op.drop_index(op.f('ix_finance_expense_claims_id'), table_name='finance_expense_claims')
    op.drop_index(op.f('ix_finance_expense_claims_claim_number'), table_name='finance_expense_claims')
    op.drop_table('finance_expense_claims')
    op.drop_index(op.f('ix_finance_budget_variances_tenant_id'), table_name='finance_budget_variances')
    op.drop_index(op.f('ix_finance_budget_variances_id'), table_name='finance_budget_variances')
    op.drop_table('finance_budget_variances')
    op.drop_index(op.f('ix_finance_tax_filings_tenant_id'), table_name='finance_tax_filings')
    op.drop_index(op.f('ix_finance_tax_filings_id'), table_name='finance_tax_filings')
    op.drop_table('finance_tax_filings')
    op.drop_index(op.f('ix_finance_journal_entries_tenant_id'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_id'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_entry_number'), table_name='finance_journal_entries')
    op.drop_table('finance_journal_entries')
    op.drop_index(op.f('ix_finance_invoices_tenant_id'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_invoice_number'), table_name='finance_invoices')
    op.drop_index(op.f('ix_finance_invoices_id'), table_name='finance_invoices')
    op.drop_table('finance_invoices')
    op.drop_index(op.f('ix_finance_expense_policies_tenant_id'), table_name='finance_expense_policies')
    op.drop_index(op.f('ix_finance_expense_policies_id'), table_name='finance_expense_policies')
    op.drop_table('finance_expense_policies')
    op.drop_index(op.f('ix_finance_budgets_tenant_id'), table_name='finance_budgets')
    op.drop_index(op.f('ix_finance_budgets_id'), table_name='finance_budgets')
    op.drop_table('finance_budgets')
    op.drop_index(op.f('ix_finance_budget_forecasts_tenant_id'), table_name='finance_budget_forecasts')
    op.drop_index(op.f('ix_finance_budget_forecasts_id'), table_name='finance_budget_forecasts')
    op.drop_table('finance_budget_forecasts')
    op.drop_index(op.f('ix_finance_accounts_tenant_id'), table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_id'), table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_code'), table_name='finance_accounts')
    op.drop_table('finance_accounts')
    # ### end Alembic commands ###
