"""create_hrms_tables

Revision ID: 7b99d68f2a47
Revises: c65a8f6c0cae
Create Date: 2026-07-10 16:00:56.944183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b99d68f2a47'
down_revision: Union[str, Sequence[str], None] = 'c65a8f6c0cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_bank_accounts',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('ifsc_swift_code', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_bank_accounts_employee_id'), 'employee_bank_accounts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_bank_accounts_id'), 'employee_bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_employee_bank_accounts_tenant_id'), 'employee_bank_accounts', ['tenant_id'], unique=False)
    op.create_table('employee_certifications',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('certification_name', sa.String(), nullable=False),
    sa.Column('issuing_authority', sa.String(), nullable=False),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('credential_url', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_certifications_employee_id'), 'employee_certifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_certifications_id'), 'employee_certifications', ['id'], unique=False)
    op.create_index(op.f('ix_employee_certifications_tenant_id'), 'employee_certifications', ['tenant_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('skill_type', sa.String(), nullable=False),
    sa.Column('proficiency_level', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_id'), 'employee_skills', ['id'], unique=False)
    op.create_index(op.f('ix_employee_skills_tenant_id'), 'employee_skills', ['tenant_id'], unique=False)
    op.create_table('employee_timelines',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_timelines_employee_id'), 'employee_timelines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_timelines_id'), 'employee_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_employee_timelines_tenant_id'), 'employee_timelines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_timelines_tenant_id'), table_name='employee_timelines')
    op.drop_index(op.f('ix_employee_timelines_id'), table_name='employee_timelines')
    op.drop_index(op.f('ix_employee_timelines_employee_id'), table_name='employee_timelines')
    op.drop_table('employee_timelines')
    op.drop_index(op.f('ix_employee_skills_tenant_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employee_certifications_tenant_id'), table_name='employee_certifications')
    op.drop_index(op.f('ix_employee_certifications_id'), table_name='employee_certifications')
    op.drop_index(op.f('ix_employee_certifications_employee_id'), table_name='employee_certifications')
    op.drop_table('employee_certifications')
    op.drop_index(op.f('ix_employee_bank_accounts_tenant_id'), table_name='employee_bank_accounts')
    op.drop_index(op.f('ix_employee_bank_accounts_id'), table_name='employee_bank_accounts')
    op.drop_index(op.f('ix_employee_bank_accounts_employee_id'), table_name='employee_bank_accounts')
    op.drop_table('employee_bank_accounts')
    # ### end Alembic commands ###
