"""create_payroll_extended_tables

Revision ID: 838623e829c0
Revises: 463afa9ad6a0
Create Date: 2026-07-10 17:35:23.778641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838623e829c0'
down_revision: Union[str, Sequence[str], None] = '463afa9ad6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_calendars',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('processing_date', sa.Integer(), nullable=False),
    sa.Column('disbursement_date', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_calendars_id'), 'payroll_calendars', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_calendars_tenant_id'), 'payroll_calendars', ['tenant_id'], unique=False)
    op.create_table('pay_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['payroll_calendars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_groups_id'), 'pay_groups', ['id'], unique=False)
    op.create_index(op.f('ix_pay_groups_tenant_id'), 'pay_groups', ['tenant_id'], unique=False)
    op.create_table('payroll_adjustments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_adjustments_employee_id'), 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_id'), 'payroll_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_payroll_run_id'), 'payroll_adjustments', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_tenant_id'), 'payroll_adjustments', ['tenant_id'], unique=False)
    op.create_table('payroll_ledgers',
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('disbursed_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_ledgers_employee_id'), 'payroll_ledgers', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_ledgers_id'), 'payroll_ledgers', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_ledgers_payroll_run_id'), 'payroll_ledgers', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_ledgers_tenant_id'), 'payroll_ledgers', ['tenant_id'], unique=False)
    op.create_table('payroll_loans',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('principal_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('emi_amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('paid_installments', sa.Integer(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_loans_employee_id'), 'payroll_loans', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_loans_id'), 'payroll_loans', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_loans_tenant_id'), 'payroll_loans', ['tenant_id'], unique=False)
    op.create_table('payroll_reimbursements',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claim_date', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_reimbursements_employee_id'), 'payroll_reimbursements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_reimbursements_id'), 'payroll_reimbursements', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_reimbursements_tenant_id'), 'payroll_reimbursements', ['tenant_id'], unique=False)
    op.create_table('employee_salaries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=True),
    sa.Column('pay_group_id', sa.UUID(), nullable=True),
    sa.Column('ctc', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revisions_json', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_group_id'], ['pay_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salaries_employee_id'), 'employee_salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_id'), 'employee_salaries', ['id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_tenant_id'), 'employee_salaries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_salaries_tenant_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_employee_id'), table_name='employee_salaries')
    op.drop_table('employee_salaries')
    op.drop_index(op.f('ix_payroll_reimbursements_tenant_id'), table_name='payroll_reimbursements')
    op.drop_index(op.f('ix_payroll_reimbursements_id'), table_name='payroll_reimbursements')
    op.drop_index(op.f('ix_payroll_reimbursements_employee_id'), table_name='payroll_reimbursements')
    op.drop_table('payroll_reimbursements')
    op.drop_index(op.f('ix_payroll_loans_tenant_id'), table_name='payroll_loans')
    op.drop_index(op.f('ix_payroll_loans_id'), table_name='payroll_loans')
    op.drop_index(op.f('ix_payroll_loans_employee_id'), table_name='payroll_loans')
    op.drop_table('payroll_loans')
    op.drop_index(op.f('ix_payroll_ledgers_tenant_id'), table_name='payroll_ledgers')
    op.drop_index(op.f('ix_payroll_ledgers_payroll_run_id'), table_name='payroll_ledgers')
    op.drop_index(op.f('ix_payroll_ledgers_id'), table_name='payroll_ledgers')
    op.drop_index(op.f('ix_payroll_ledgers_employee_id'), table_name='payroll_ledgers')
    op.drop_table('payroll_ledgers')
    op.drop_index(op.f('ix_payroll_adjustments_tenant_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_payroll_run_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_employee_id'), table_name='payroll_adjustments')
    op.drop_table('payroll_adjustments')
    op.drop_index(op.f('ix_pay_groups_tenant_id'), table_name='pay_groups')
    op.drop_index(op.f('ix_pay_groups_id'), table_name='pay_groups')
    op.drop_table('pay_groups')
    op.drop_index(op.f('ix_payroll_calendars_tenant_id'), table_name='payroll_calendars')
    op.drop_index(op.f('ix_payroll_calendars_id'), table_name='payroll_calendars')
    op.drop_table('payroll_calendars')
    # ### end Alembic commands ###
