"""add_crm_modules

Revision ID: 84f96c264093
Revises: 71bb7839308a
Create Date: 2026-07-16 14:29:31.609449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f96c264093'
down_revision: Union[str, Sequence[str], None] = '71bb7839308a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_customers',
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('gst', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('relationship_score', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_customers_id'), 'crm_customers', ['id'], unique=False)
    op.create_index(op.f('ix_crm_customers_tenant_id'), 'crm_customers', ['tenant_id'], unique=False)
    op.create_table('crm_leads',
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('lead_source', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('expected_close', sa.Date(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lead_owner', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
    op.create_index(op.f('ix_crm_leads_tenant_id'), 'crm_leads', ['tenant_id'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_id'), 'crm_contacts', ['id'], unique=False)
    op.create_table('crm_quotations',
    sa.Column('quotation_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_quotations_id'), 'crm_quotations', ['id'], unique=False)
    op.create_index(op.f('ix_crm_quotations_quotation_number'), 'crm_quotations', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_crm_quotations_tenant_id'), 'crm_quotations', ['tenant_id'], unique=False)
    op.create_table('crm_tasks',
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tasks_id'), 'crm_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_tenant_id'), 'crm_tasks', ['tenant_id'], unique=False)
    op.create_table('crm_quotation_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['crm_quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_quotation_items_id'), 'crm_quotation_items', ['id'], unique=False)
    op.create_table('crm_sales_orders',
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('courier_partner', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['crm_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['crm_quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sales_orders_id'), 'crm_sales_orders', ['id'], unique=False)
    op.create_index(op.f('ix_crm_sales_orders_order_number'), 'crm_sales_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_crm_sales_orders_tenant_id'), 'crm_sales_orders', ['tenant_id'], unique=False)
    op.create_table('crm_sales_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['crm_sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sales_order_items_id'), 'crm_sales_order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_sales_order_items_id'), table_name='crm_sales_order_items')
    op.drop_table('crm_sales_order_items')
    op.drop_index(op.f('ix_crm_sales_orders_tenant_id'), table_name='crm_sales_orders')
    op.drop_index(op.f('ix_crm_sales_orders_order_number'), table_name='crm_sales_orders')
    op.drop_index(op.f('ix_crm_sales_orders_id'), table_name='crm_sales_orders')
    op.drop_table('crm_sales_orders')
    op.drop_index(op.f('ix_crm_quotation_items_id'), table_name='crm_quotation_items')
    op.drop_table('crm_quotation_items')
    op.drop_index(op.f('ix_crm_tasks_tenant_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_id'), table_name='crm_tasks')
    op.drop_table('crm_tasks')
    op.drop_index(op.f('ix_crm_quotations_tenant_id'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_quotation_number'), table_name='crm_quotations')
    op.drop_index(op.f('ix_crm_quotations_id'), table_name='crm_quotations')
    op.drop_table('crm_quotations')
    op.drop_index(op.f('ix_crm_contacts_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_crm_leads_tenant_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_customers_tenant_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_id'), table_name='crm_customers')
    op.drop_table('crm_customers')
    # ### end Alembic commands ###
