"""Add lms tables

Revision ID: 96f8deb97e7c
Revises: 058696582793
Create Date: 2026-07-11 15:01:26.906953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f8deb97e7c'
down_revision: Union[str, Sequence[str], None] = '058696582793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_courses',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_courses_id'), 'lms_courses', ['id'], unique=False)
    op.create_index(op.f('ix_lms_courses_tenant_id'), 'lms_courses', ['tenant_id'], unique=False)
    op.create_table('lms_enrollments',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_enrollments_course_id'), 'lms_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_lms_enrollments_employee_id'), 'lms_enrollments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_lms_enrollments_id'), 'lms_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_lms_enrollments_tenant_id'), 'lms_enrollments', ['tenant_id'], unique=False)
    op.create_table('lms_lessons',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_lessons_course_id'), 'lms_lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_lms_lessons_id'), 'lms_lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lms_lessons_tenant_id'), 'lms_lessons', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lms_lessons_tenant_id'), table_name='lms_lessons')
    op.drop_index(op.f('ix_lms_lessons_id'), table_name='lms_lessons')
    op.drop_index(op.f('ix_lms_lessons_course_id'), table_name='lms_lessons')
    op.drop_table('lms_lessons')
    op.drop_index(op.f('ix_lms_enrollments_tenant_id'), table_name='lms_enrollments')
    op.drop_index(op.f('ix_lms_enrollments_id'), table_name='lms_enrollments')
    op.drop_index(op.f('ix_lms_enrollments_employee_id'), table_name='lms_enrollments')
    op.drop_index(op.f('ix_lms_enrollments_course_id'), table_name='lms_enrollments')
    op.drop_table('lms_enrollments')
    op.drop_index(op.f('ix_lms_courses_tenant_id'), table_name='lms_courses')
    op.drop_index(op.f('ix_lms_courses_id'), table_name='lms_courses')
    op.drop_table('lms_courses')
    # ### end Alembic commands ###
