"""create_recruitment_tables

Revision ID: 97556a406034
Revises: 838623e829c0
Create Date: 2026-07-10 17:43:16.912007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97556a406034'
down_revision: Union[str, Sequence[str], None] = '838623e829c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('current_ctc', sa.Float(), nullable=False),
    sa.Column('expected_ctc', sa.Float(), nullable=False),
    sa.Column('notice_period', sa.Integer(), nullable=False),
    sa.Column('preferred_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('resume_text', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_tenant_id'), 'candidates', ['tenant_id'], unique=False)
    op.create_table('hiring_plans',
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('position_title', sa.String(), nullable=False),
    sa.Column('hiring_count', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hiring_plans_id'), 'hiring_plans', ['id'], unique=False)
    op.create_index(op.f('ix_hiring_plans_tenant_id'), 'hiring_plans', ['tenant_id'], unique=False)
    op.create_table('assessments',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('assessment_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_candidate_id'), 'assessments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_tenant_id'), 'assessments', ['tenant_id'], unique=False)
    op.create_table('background_verification',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('identity_status', sa.String(), nullable=False),
    sa.Column('education_status', sa.String(), nullable=False),
    sa.Column('employment_status', sa.String(), nullable=False),
    sa.Column('criminal_status', sa.String(), nullable=False),
    sa.Column('reference_status', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_verification_candidate_id'), 'background_verification', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_background_verification_id'), 'background_verification', ['id'], unique=False)
    op.create_index(op.f('ix_background_verification_tenant_id'), 'background_verification', ['tenant_id'], unique=False)
    op.create_table('candidate_education',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_education_candidate_id'), 'candidate_education', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_education_id'), 'candidate_education', ['id'], unique=False)
    op.create_table('candidate_experience',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experience_candidate_id'), 'candidate_experience', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_experience_id'), 'candidate_experience', ['id'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_id'), 'candidate_skills', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_tenant_id'), 'interviews', ['tenant_id'], unique=False)
    op.create_table('job_requisitions',
    sa.Column('requisition_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('hiring_manager_id', sa.UUID(), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_number')
    )
    op.create_index(op.f('ix_job_requisitions_id'), 'job_requisitions', ['id'], unique=False)
    op.create_index(op.f('ix_job_requisitions_tenant_id'), 'job_requisitions', ['tenant_id'], unique=False)
    op.create_table('offers',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('ctc', sa.Float(), nullable=False),
    sa.Column('fixed_pay', sa.Float(), nullable=False),
    sa.Column('variable_pay', sa.Float(), nullable=False),
    sa.Column('joining_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approval_history', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_candidate_id'), 'offers', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_tenant_id'), 'offers', ['tenant_id'], unique=False)
    op.create_table('recruitment_timelines',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruitment_timelines_candidate_id'), 'recruitment_timelines', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruitment_timelines_id'), 'recruitment_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_recruitment_timelines_tenant_id'), 'recruitment_timelines', ['tenant_id'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('interviewer_name', sa.String(), nullable=False),
    sa.Column('technical_rating', sa.Integer(), nullable=False),
    sa.Column('communication_rating', sa.Integer(), nullable=False),
    sa.Column('problem_solving_rating', sa.Integer(), nullable=False),
    sa.Column('cultural_fit_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedback_id'), 'interview_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_interview_id'), 'interview_feedback', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_tenant_id'), 'interview_feedback', ['tenant_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_job_postings_requisition_id'), 'job_postings', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_job_postings_tenant_id'), 'job_postings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_tenant_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_requisition_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_interview_feedback_tenant_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_interview_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_recruitment_timelines_tenant_id'), table_name='recruitment_timelines')
    op.drop_index(op.f('ix_recruitment_timelines_id'), table_name='recruitment_timelines')
    op.drop_index(op.f('ix_recruitment_timelines_candidate_id'), table_name='recruitment_timelines')
    op.drop_table('recruitment_timelines')
    op.drop_index(op.f('ix_offers_tenant_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_candidate_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_job_requisitions_tenant_id'), table_name='job_requisitions')
    op.drop_index(op.f('ix_job_requisitions_id'), table_name='job_requisitions')
    op.drop_table('job_requisitions')
    op.drop_index(op.f('ix_interviews_tenant_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_candidate_skills_id'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_candidate_experience_id'), table_name='candidate_experience')
    op.drop_index(op.f('ix_candidate_experience_candidate_id'), table_name='candidate_experience')
    op.drop_table('candidate_experience')
    op.drop_index(op.f('ix_candidate_education_id'), table_name='candidate_education')
    op.drop_index(op.f('ix_candidate_education_candidate_id'), table_name='candidate_education')
    op.drop_table('candidate_education')
    op.drop_index(op.f('ix_background_verification_tenant_id'), table_name='background_verification')
    op.drop_index(op.f('ix_background_verification_id'), table_name='background_verification')
    op.drop_index(op.f('ix_background_verification_candidate_id'), table_name='background_verification')
    op.drop_table('background_verification')
    op.drop_index(op.f('ix_assessments_tenant_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_candidate_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_hiring_plans_tenant_id'), table_name='hiring_plans')
    op.drop_index(op.f('ix_hiring_plans_id'), table_name='hiring_plans')
    op.drop_table('hiring_plans')
    op.drop_index(op.f('ix_candidates_tenant_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
