"""Add performance tables

Revision ID: 9c50020b26c0
Revises: 619c5446685a
Create Date: 2026-07-11 14:42:56.444621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c50020b26c0'
down_revision: Union[str, Sequence[str], None] = '619c5446685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_id'), 'competencies', ['id'], unique=False)
    op.create_index(op.f('ix_competencies_tenant_id'), 'competencies', ['tenant_id'], unique=False)
    op.create_table('performance_cycles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_cycles_id'), 'performance_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_performance_cycles_tenant_id'), 'performance_cycles', ['tenant_id'], unique=False)
    op.create_table('performance_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goals_weight', sa.Float(), nullable=False),
    sa.Column('competencies_weight', sa.Float(), nullable=False),
    sa.Column('rating_scale', sa.String(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_templates_id'), 'performance_templates', ['id'], unique=False)
    op.create_index(op.f('ix_performance_templates_tenant_id'), 'performance_templates', ['tenant_id'], unique=False)
    op.create_table('competency_scores',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('evaluator_role', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_scores_employee_id'), 'competency_scores', ['employee_id'], unique=False)
    op.create_index(op.f('ix_competency_scores_id'), 'competency_scores', ['id'], unique=False)
    op.create_index(op.f('ix_competency_scores_tenant_id'), 'competency_scores', ['tenant_id'], unique=False)
    op.create_table('feedback_360',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comments', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_360_employee_id'), 'feedback_360', ['employee_id'], unique=False)
    op.create_index(op.f('ix_feedback_360_id'), 'feedback_360', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_360_tenant_id'), 'feedback_360', ['tenant_id'], unique=False)
    op.create_table('goals',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_employee_id'), 'goals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_tenant_id'), 'goals', ['tenant_id'], unique=False)
    op.create_table('performance_journals',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('entry', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_journals_employee_id'), 'performance_journals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_journals_id'), 'performance_journals', ['id'], unique=False)
    op.create_index(op.f('ix_performance_journals_tenant_id'), 'performance_journals', ['tenant_id'], unique=False)
    op.create_table('performance_promotions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('nominated_by', sa.UUID(), nullable=True),
    sa.Column('target_designation', sa.String(), nullable=False),
    sa.Column('proposed_ctc', sa.Float(), nullable=False),
    sa.Column('justification', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nominated_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_promotions_employee_id'), 'performance_promotions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_promotions_id'), 'performance_promotions', ['id'], unique=False)
    op.create_index(op.f('ix_performance_promotions_tenant_id'), 'performance_promotions', ['tenant_id'], unique=False)
    op.create_table('performance_recognitions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('giver_id', sa.UUID(), nullable=True),
    sa.Column('award_type', sa.String(), nullable=False),
    sa.Column('citation', sa.String(), nullable=False),
    sa.Column('awarded_date', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giver_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_recognitions_employee_id'), 'performance_recognitions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_recognitions_id'), 'performance_recognitions', ['id'], unique=False)
    op.create_index(op.f('ix_performance_recognitions_tenant_id'), 'performance_recognitions', ['tenant_id'], unique=False)
    op.create_table('performance_reviews',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('self_rating', sa.Float(), nullable=True),
    sa.Column('self_comments', sa.String(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('manager_rating', sa.Float(), nullable=True),
    sa.Column('manager_comments', sa.String(), nullable=True),
    sa.Column('calibrated_rating', sa.Float(), nullable=True),
    sa.Column('calibration_comments', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['performance_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reviews_employee_id'), 'performance_reviews', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_reviews_id'), 'performance_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_performance_reviews_tenant_id'), 'performance_reviews', ['tenant_id'], unique=False)
    op.create_table('performance_timelines',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_timelines_employee_id'), 'performance_timelines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_timelines_id'), 'performance_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_performance_timelines_tenant_id'), 'performance_timelines', ['tenant_id'], unique=False)
    op.create_table('pip_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('expected_outcomes', sa.String(), nullable=False),
    sa.Column('coaching_notes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('final_assessment', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pip_records_employee_id'), 'pip_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pip_records_id'), 'pip_records', ['id'], unique=False)
    op.create_index(op.f('ix_pip_records_tenant_id'), 'pip_records', ['tenant_id'], unique=False)
    op.create_table('succession_plans',
    sa.Column('position_name', sa.String(), nullable=False),
    sa.Column('incumbent_id', sa.UUID(), nullable=True),
    sa.Column('successor_id', sa.UUID(), nullable=False),
    sa.Column('readiness', sa.String(), nullable=False),
    sa.Column('performance_rating', sa.Float(), nullable=True),
    sa.Column('potential_rating', sa.Float(), nullable=True),
    sa.Column('development_needs', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incumbent_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['successor_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_succession_plans_id'), 'succession_plans', ['id'], unique=False)
    op.create_index(op.f('ix_succession_plans_position_name'), 'succession_plans', ['position_name'], unique=False)
    op.create_index(op.f('ix_succession_plans_tenant_id'), 'succession_plans', ['tenant_id'], unique=False)
    op.create_table('key_results',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_results_goal_id'), 'key_results', ['goal_id'], unique=False)
    op.create_index(op.f('ix_key_results_id'), 'key_results', ['id'], unique=False)
    op.create_index(op.f('ix_key_results_tenant_id'), 'key_results', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_results_tenant_id'), table_name='key_results')
    op.drop_index(op.f('ix_key_results_id'), table_name='key_results')
    op.drop_index(op.f('ix_key_results_goal_id'), table_name='key_results')
    op.drop_table('key_results')
    op.drop_index(op.f('ix_succession_plans_tenant_id'), table_name='succession_plans')
    op.drop_index(op.f('ix_succession_plans_position_name'), table_name='succession_plans')
    op.drop_index(op.f('ix_succession_plans_id'), table_name='succession_plans')
    op.drop_table('succession_plans')
    op.drop_index(op.f('ix_pip_records_tenant_id'), table_name='pip_records')
    op.drop_index(op.f('ix_pip_records_id'), table_name='pip_records')
    op.drop_index(op.f('ix_pip_records_employee_id'), table_name='pip_records')
    op.drop_table('pip_records')
    op.drop_index(op.f('ix_performance_timelines_tenant_id'), table_name='performance_timelines')
    op.drop_index(op.f('ix_performance_timelines_id'), table_name='performance_timelines')
    op.drop_index(op.f('ix_performance_timelines_employee_id'), table_name='performance_timelines')
    op.drop_table('performance_timelines')
    op.drop_index(op.f('ix_performance_reviews_tenant_id'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_id'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_employee_id'), table_name='performance_reviews')
    op.drop_table('performance_reviews')
    op.drop_index(op.f('ix_performance_recognitions_tenant_id'), table_name='performance_recognitions')
    op.drop_index(op.f('ix_performance_recognitions_id'), table_name='performance_recognitions')
    op.drop_index(op.f('ix_performance_recognitions_employee_id'), table_name='performance_recognitions')
    op.drop_table('performance_recognitions')
    op.drop_index(op.f('ix_performance_promotions_tenant_id'), table_name='performance_promotions')
    op.drop_index(op.f('ix_performance_promotions_id'), table_name='performance_promotions')
    op.drop_index(op.f('ix_performance_promotions_employee_id'), table_name='performance_promotions')
    op.drop_table('performance_promotions')
    op.drop_index(op.f('ix_performance_journals_tenant_id'), table_name='performance_journals')
    op.drop_index(op.f('ix_performance_journals_id'), table_name='performance_journals')
    op.drop_index(op.f('ix_performance_journals_employee_id'), table_name='performance_journals')
    op.drop_table('performance_journals')
    op.drop_index(op.f('ix_goals_tenant_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_employee_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_feedback_360_tenant_id'), table_name='feedback_360')
    op.drop_index(op.f('ix_feedback_360_id'), table_name='feedback_360')
    op.drop_index(op.f('ix_feedback_360_employee_id'), table_name='feedback_360')
    op.drop_table('feedback_360')
    op.drop_index(op.f('ix_competency_scores_tenant_id'), table_name='competency_scores')
    op.drop_index(op.f('ix_competency_scores_id'), table_name='competency_scores')
    op.drop_index(op.f('ix_competency_scores_employee_id'), table_name='competency_scores')
    op.drop_table('competency_scores')
    op.drop_index(op.f('ix_performance_templates_tenant_id'), table_name='performance_templates')
    op.drop_index(op.f('ix_performance_templates_id'), table_name='performance_templates')
    op.drop_table('performance_templates')
    op.drop_index(op.f('ix_performance_cycles_tenant_id'), table_name='performance_cycles')
    op.drop_index(op.f('ix_performance_cycles_id'), table_name='performance_cycles')
    op.drop_table('performance_cycles')
    op.drop_index(op.f('ix_competencies_tenant_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_id'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
