"""Add ai interview tables

Revision ID: 9ea071317454
Revises: 9c50020b26c0
Create Date: 2026-07-11 14:48:03.184728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea071317454'
down_revision: Union[str, Sequence[str], None] = '9c50020b26c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interview_sessions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('transcript_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interview_sessions_candidate_id'), 'ai_interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ai_interview_sessions_id'), 'ai_interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interview_sessions_tenant_id'), 'ai_interview_sessions', ['tenant_id'], unique=False)
    op.create_table('ai_interview_questions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interview_questions_id'), 'ai_interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interview_questions_session_id'), 'ai_interview_questions', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_interview_questions_tenant_id'), 'ai_interview_questions', ['tenant_id'], unique=False)
    op.create_table('ai_interview_responses',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('duration_taken', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('correctness_score', sa.Float(), nullable=True),
    sa.Column('evaluation_notes', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['ai_interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interview_responses_id'), 'ai_interview_responses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interview_responses_question_id'), 'ai_interview_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_ai_interview_responses_session_id'), 'ai_interview_responses', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_interview_responses_tenant_id'), 'ai_interview_responses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interview_responses_tenant_id'), table_name='ai_interview_responses')
    op.drop_index(op.f('ix_ai_interview_responses_session_id'), table_name='ai_interview_responses')
    op.drop_index(op.f('ix_ai_interview_responses_question_id'), table_name='ai_interview_responses')
    op.drop_index(op.f('ix_ai_interview_responses_id'), table_name='ai_interview_responses')
    op.drop_table('ai_interview_responses')
    op.drop_index(op.f('ix_ai_interview_questions_tenant_id'), table_name='ai_interview_questions')
    op.drop_index(op.f('ix_ai_interview_questions_session_id'), table_name='ai_interview_questions')
    op.drop_index(op.f('ix_ai_interview_questions_id'), table_name='ai_interview_questions')
    op.drop_table('ai_interview_questions')
    op.drop_index(op.f('ix_ai_interview_sessions_tenant_id'), table_name='ai_interview_sessions')
    op.drop_index(op.f('ix_ai_interview_sessions_id'), table_name='ai_interview_sessions')
    op.drop_index(op.f('ix_ai_interview_sessions_candidate_id'), table_name='ai_interview_sessions')
    op.drop_table('ai_interview_sessions')
    # ### end Alembic commands ###
