"""create_leave_extended_tables

Revision ID: b18dcee73e5b
Revises: fcebfa6edd7b
Create Date: 2026-07-10 16:40:10.689117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18dcee73e5b'
down_revision: Union[str, Sequence[str], None] = 'fcebfa6edd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_carry_forwards',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('days_carried', sa.Float(), nullable=False),
    sa.Column('days_expired', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_carry_forwards_employee_id'), 'leave_carry_forwards', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_carry_forwards_id'), 'leave_carry_forwards', ['id'], unique=False)
    op.create_index(op.f('ix_leave_carry_forwards_leave_type_id'), 'leave_carry_forwards', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_carry_forwards_tenant_id'), 'leave_carry_forwards', ['tenant_id'], unique=False)
    op.create_table('leave_encashments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_encashments_employee_id'), 'leave_encashments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_encashments_id'), 'leave_encashments', ['id'], unique=False)
    op.create_index(op.f('ix_leave_encashments_leave_type_id'), 'leave_encashments', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_encashments_tenant_id'), 'leave_encashments', ['tenant_id'], unique=False)
    op.create_table('leave_ledgers',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=False),
    sa.Column('new_balance', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_ledgers_employee_id'), 'leave_ledgers', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_ledgers_id'), 'leave_ledgers', ['id'], unique=False)
    op.create_index(op.f('ix_leave_ledgers_leave_type_id'), 'leave_ledgers', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_ledgers_tenant_id'), 'leave_ledgers', ['tenant_id'], unique=False)
    op.create_table('leave_timelines',
    sa.Column('leave_application_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['leave_application_id'], ['leave_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_timelines_id'), 'leave_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_leave_timelines_leave_application_id'), 'leave_timelines', ['leave_application_id'], unique=False)
    op.create_index(op.f('ix_leave_timelines_tenant_id'), 'leave_timelines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_timelines_tenant_id'), table_name='leave_timelines')
    op.drop_index(op.f('ix_leave_timelines_leave_application_id'), table_name='leave_timelines')
    op.drop_index(op.f('ix_leave_timelines_id'), table_name='leave_timelines')
    op.drop_table('leave_timelines')
    op.drop_index(op.f('ix_leave_ledgers_tenant_id'), table_name='leave_ledgers')
    op.drop_index(op.f('ix_leave_ledgers_leave_type_id'), table_name='leave_ledgers')
    op.drop_index(op.f('ix_leave_ledgers_id'), table_name='leave_ledgers')
    op.drop_index(op.f('ix_leave_ledgers_employee_id'), table_name='leave_ledgers')
    op.drop_table('leave_ledgers')
    op.drop_index(op.f('ix_leave_encashments_tenant_id'), table_name='leave_encashments')
    op.drop_index(op.f('ix_leave_encashments_leave_type_id'), table_name='leave_encashments')
    op.drop_index(op.f('ix_leave_encashments_id'), table_name='leave_encashments')
    op.drop_index(op.f('ix_leave_encashments_employee_id'), table_name='leave_encashments')
    op.drop_table('leave_encashments')
    op.drop_index(op.f('ix_leave_carry_forwards_tenant_id'), table_name='leave_carry_forwards')
    op.drop_index(op.f('ix_leave_carry_forwards_leave_type_id'), table_name='leave_carry_forwards')
    op.drop_index(op.f('ix_leave_carry_forwards_id'), table_name='leave_carry_forwards')
    op.drop_index(op.f('ix_leave_carry_forwards_employee_id'), table_name='leave_carry_forwards')
    op.drop_table('leave_carry_forwards')
    # ### end Alembic commands ###
