"""Add community tables

Revision ID: cb1a84e871ea
Revises: 96f8deb97e7c
Create Date: 2026-07-11 15:11:35.359861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1a84e871ea'
down_revision: Union[str, Sequence[str], None] = '96f8deb97e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_polls',
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_polls_id'), 'community_polls', ['id'], unique=False)
    op.create_index(op.f('ix_community_polls_tenant_id'), 'community_polls', ['tenant_id'], unique=False)
    op.create_table('community_announcements',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_announcements_id'), 'community_announcements', ['id'], unique=False)
    op.create_index(op.f('ix_community_announcements_tenant_id'), 'community_announcements', ['tenant_id'], unique=False)
    op.create_table('community_poll_votes',
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['community_polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_poll_votes_employee_id'), 'community_poll_votes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_community_poll_votes_id'), 'community_poll_votes', ['id'], unique=False)
    op.create_index(op.f('ix_community_poll_votes_poll_id'), 'community_poll_votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_community_poll_votes_tenant_id'), 'community_poll_votes', ['tenant_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_employee_id'), 'community_posts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_tenant_id'), 'community_posts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_posts_tenant_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_employee_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_poll_votes_tenant_id'), table_name='community_poll_votes')
    op.drop_index(op.f('ix_community_poll_votes_poll_id'), table_name='community_poll_votes')
    op.drop_index(op.f('ix_community_poll_votes_id'), table_name='community_poll_votes')
    op.drop_index(op.f('ix_community_poll_votes_employee_id'), table_name='community_poll_votes')
    op.drop_table('community_poll_votes')
    op.drop_index(op.f('ix_community_announcements_tenant_id'), table_name='community_announcements')
    op.drop_index(op.f('ix_community_announcements_id'), table_name='community_announcements')
    op.drop_table('community_announcements')
    op.drop_index(op.f('ix_community_polls_tenant_id'), table_name='community_polls')
    op.drop_index(op.f('ix_community_polls_id'), table_name='community_polls')
    op.drop_table('community_polls')
    # ### end Alembic commands ###
