"""upgrade_inventory_module

Revision ID: d3ab6502c05c
Revises: 4e3db982736b
Create Date: 2026-07-16 10:46:29.054112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3ab6502c05c'
down_revision: Union[str, Sequence[str], None] = '4e3db982736b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landed_cost_vouchers',
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), nullable=False),
    sa.Column('distribute_by', sa.String(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'voucher_number', name='uq_tenant_lcv_number')
    )
    op.create_index(op.f('ix_landed_cost_vouchers_id'), 'landed_cost_vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_landed_cost_vouchers_tenant_id'), 'landed_cost_vouchers', ['tenant_id'], unique=False)
    op.create_table('landed_cost_items',
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('purchase_receipt_id', sa.String(), nullable=False),
    sa.Column('receipt_quantity', sa.Float(), nullable=False),
    sa.Column('allocated_expense', sa.Float(), nullable=False),
    sa.Column('adjusted_unit_cost', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['landed_cost_vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landed_cost_items_id'), 'landed_cost_items', ['id'], unique=False)
    op.create_index(op.f('ix_landed_cost_items_tenant_id'), 'landed_cost_items', ['tenant_id'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('reserved_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reserved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_reservations_id'), 'stock_reservations', ['id'], unique=False)
    op.create_index(op.f('ix_stock_reservations_tenant_id'), 'stock_reservations', ['tenant_id'], unique=False)
    op.create_table('inventory_quality_inspections',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Float(), nullable=False),
    sa.Column('failed_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_quality_inspections_id'), 'inventory_quality_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_quality_inspections_tenant_id'), 'inventory_quality_inspections', ['tenant_id'], unique=False)
    op.create_table('serial_asset_assignments',
    sa.Column('serial_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('condition_on_assign', sa.String(), nullable=False),
    sa.Column('condition_on_return', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serial_id'], ['stock_serials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serial_asset_assignments_id'), 'serial_asset_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_serial_asset_assignments_tenant_id'), 'serial_asset_assignments', ['tenant_id'], unique=False)
    op.alter_column('asset_health', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('asset_health', 'health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_health', 'operating_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_health', 'runtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_health', 'downtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_health', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_health', 'vibration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_health', 'power_consumption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('asset_health_asset_id_fkey'), 'asset_health', type_='foreignkey')
    op.create_foreign_key(None, 'asset_health', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('asset_hierarchy', 'relation_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('asset_hierarchy_child_asset_id_fkey'), 'asset_hierarchy', type_='foreignkey')
    op.drop_constraint(op.f('asset_hierarchy_parent_asset_id_fkey'), 'asset_hierarchy', type_='foreignkey')
    op.create_foreign_key(None, 'asset_hierarchy', 'maintenance_assets', ['child_asset_id'], ['id'])
    op.create_foreign_key(None, 'asset_hierarchy', 'maintenance_assets', ['parent_asset_id'], ['id'])
    op.alter_column('bill_of_materials', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bill_of_materials', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bill_of_materials', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_bom_number'), 'bill_of_materials', type_='unique')
    op.create_index(op.f('ix_bill_of_materials_bom_number'), 'bill_of_materials', ['bom_number'], unique=False)
    op.drop_constraint(op.f('bill_of_materials_item_id_fkey'), 'bill_of_materials', type_='foreignkey')
    op.create_foreign_key(None, 'bill_of_materials', 'inventory_items', ['item_id'], ['id'])
    op.alter_column('bom_components', 'uom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('bom_components_item_id_fkey'), 'bom_components', type_='foreignkey')
    op.drop_constraint(op.f('bom_components_bom_id_fkey'), 'bom_components', type_='foreignkey')
    op.create_foreign_key(None, 'bom_components', 'inventory_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'bom_components', 'bill_of_materials', ['bom_id'], ['id'])
    op.alter_column('carriers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('delivery_routes', 'optimized',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('delivery_routes_shipment_id_fkey'), 'delivery_routes', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_routes', 'shipments', ['shipment_id'], ['id'])
    op.alter_column('dispatch_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('dispatch_orders_shipment_id_fkey'), 'dispatch_orders', type_='foreignkey')
    op.create_foreign_key(None, 'dispatch_orders', 'shipments', ['shipment_id'], ['id'])
    op.alter_column('drivers', 'availability_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fleet_vehicles', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fleet_vehicles', 'maintenance_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('freight_costs_shipment_id_fkey'), 'freight_costs', type_='foreignkey')
    op.create_foreign_key(None, 'freight_costs', 'shipments', ['shipment_id'], ['id'])
    op.alter_column('gps_tracking', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('inspection_checklists', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('machine_performance', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('machine_performance', 'runtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'downtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'idle_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'maintenance_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'availability_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'performance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'quality_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('machine_performance', 'oee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('machine_performance_machine_id_fkey'), 'machine_performance', type_='foreignkey')
    op.create_foreign_key(None, 'machine_performance', 'machines', ['machine_id'], ['id'])
    op.alter_column('machines', 'installation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('machines', 'calibration_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('machines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('machines', 'utilization_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_machine_code'), 'machines', type_='unique')
    op.create_index(op.f('ix_machines_machine_code'), 'machines', ['machine_code'], unique=False)
    op.alter_column('maintenance_analytics', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_analytics', 'breakdowns_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('maintenance_analytics', 'total_maintenance_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance_analytics', 'labor_hours_logged',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('maintenance_analytics_plant_id_fkey'), 'maintenance_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_analytics', 'manufacturing_plants', ['plant_id'], ['id'])
    op.alter_column('maintenance_assets', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_assets', 'installation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_assets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_assets_plant_id_fkey'), 'maintenance_assets', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_assets', 'manufacturing_plants', ['plant_id'], ['id'])
    op.alter_column('maintenance_calendar', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_calendar_asset_id_fkey'), 'maintenance_calendar', type_='foreignkey')
    op.drop_constraint(op.f('maintenance_calendar_plan_id_fkey'), 'maintenance_calendar', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_calendar', 'maintenance_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_calendar', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('maintenance_costs', 'labor_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance_costs', 'parts_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance_costs', 'downtime_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance_costs', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('maintenance_costs_work_order_id_fkey'), 'maintenance_costs', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_costs', 'maintenance_work_orders', ['work_order_id'], ['id'])
    op.alter_column('maintenance_history', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_history', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('maintenance_history_asset_id_fkey'), 'maintenance_history', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_history', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('maintenance_inspections', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_inspections_work_order_id_fkey'), 'maintenance_inspections', type_='foreignkey')
    op.drop_constraint(op.f('maintenance_inspections_asset_id_fkey'), 'maintenance_inspections', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_inspections', 'maintenance_assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_inspections', 'maintenance_work_orders', ['work_order_id'], ['id'])
    op.alter_column('maintenance_plans', 'maintenance_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_plans', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_plans', 'estimated_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('maintenance_plans_asset_id_fkey'), 'maintenance_plans', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_plans', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('maintenance_requests', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_requests', 'requested_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('maintenance_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_requests_asset_id_fkey'), 'maintenance_requests', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_requests', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('maintenance_timelines', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_timelines_request_id_fkey'), 'maintenance_timelines', type_='foreignkey')
    op.drop_constraint(op.f('maintenance_timelines_work_order_id_fkey'), 'maintenance_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_timelines', 'maintenance_requests', ['request_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_timelines', 'maintenance_work_orders', ['work_order_id'], ['id'])
    op.alter_column('maintenance_work_orders', 'maintenance_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_work_orders', 'estimated_labor_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance_work_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_work_orders_plan_id_fkey'), 'maintenance_work_orders', type_='foreignkey')
    op.drop_constraint(op.f('maintenance_work_orders_request_id_fkey'), 'maintenance_work_orders', type_='foreignkey')
    op.drop_constraint(op.f('maintenance_work_orders_asset_id_fkey'), 'maintenance_work_orders', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_work_orders', 'maintenance_assets', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_work_orders', 'maintenance_plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_work_orders', 'maintenance_requests', ['request_id'], ['id'])
    op.alter_column('manufacturing_plants', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_plant_code'), 'manufacturing_plants', type_='unique')
    op.create_index(op.f('ix_manufacturing_plants_code'), 'manufacturing_plants', ['code'], unique=False)
    op.alter_column('manufacturing_timelines', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('manufacturing_timelines_production_order_id_fkey'), 'manufacturing_timelines', type_='foreignkey')
    op.drop_constraint(op.f('manufacturing_timelines_work_order_id_fkey'), 'manufacturing_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'manufacturing_timelines', 'production_orders', ['production_order_id'], ['id'])
    op.create_foreign_key(None, 'manufacturing_timelines', 'work_orders', ['work_order_id'], ['id'])
    op.alter_column('material_consumption', 'waste_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('material_consumption_item_id_fkey'), 'material_consumption', type_='foreignkey')
    op.drop_constraint(op.f('material_consumption_work_order_id_fkey'), 'material_consumption', type_='foreignkey')
    op.create_foreign_key(None, 'material_consumption', 'inventory_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'material_consumption', 'work_orders', ['work_order_id'], ['id'])
    op.alter_column('non_conformance_reports', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_ncr_number'), 'non_conformance_reports', type_='unique')
    op.create_index(op.f('ix_non_conformance_reports_ncr_number'), 'non_conformance_reports', ['ncr_number'], unique=False)
    op.drop_constraint(op.f('non_conformance_reports_inspection_id_fkey'), 'non_conformance_reports', type_='foreignkey')
    op.create_foreign_key(None, 'non_conformance_reports', 'quality_inspections', ['inspection_id'], ['id'])
    op.alter_column('predictive_alerts', 'alert_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('predictive_alerts', 'failure_probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('predictive_alerts', 'remaining_useful_life_days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('predictive_alerts', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('predictive_alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('predictive_alerts_asset_id_fkey'), 'predictive_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'predictive_alerts', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('production_analytics', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('production_analytics', 'daily_demand',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('production_analytics', 'daily_production_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('production_analytics', 'yield_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('production_analytics', 'scrap_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('production_analytics', 'throughput_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('production_analytics', 'labor_productivity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('production_analytics_plant_id_fkey'), 'production_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'production_analytics', 'manufacturing_plants', ['plant_id'], ['id'])
    op.alter_column('production_calendars', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('production_calendars_plant_id_fkey'), 'production_calendars', type_='foreignkey')
    op.create_foreign_key(None, 'production_calendars', 'manufacturing_plants', ['plant_id'], ['id'])
    op.alter_column('production_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_production_order_number'), 'production_orders', type_='unique')
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=False)
    op.drop_constraint(op.f('production_orders_routing_id_fkey'), 'production_orders', type_='foreignkey')
    op.drop_constraint(op.f('production_orders_item_id_fkey'), 'production_orders', type_='foreignkey')
    op.drop_constraint(op.f('production_orders_plant_id_fkey'), 'production_orders', type_='foreignkey')
    op.drop_constraint(op.f('production_orders_bom_id_fkey'), 'production_orders', type_='foreignkey')
    op.drop_constraint(op.f('production_orders_work_center_id_fkey'), 'production_orders', type_='foreignkey')
    op.create_foreign_key(None, 'production_orders', 'routing_master', ['routing_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'bill_of_materials', ['bom_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'work_centers', ['work_center_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'inventory_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'manufacturing_plants', ['plant_id'], ['id'])
    op.alter_column('production_output', 'scrap_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('production_output', 'rejected_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('production_output_work_order_id_fkey'), 'production_output', type_='foreignkey')
    op.drop_constraint(op.f('production_output_item_id_fkey'), 'production_output', type_='foreignkey')
    op.create_foreign_key(None, 'production_output', 'work_orders', ['work_order_id'], ['id'])
    op.create_foreign_key(None, 'production_output', 'inventory_items', ['item_id'], ['id'])
    op.alter_column('proof_of_delivery', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('proof_of_delivery_shipment_id_fkey'), 'proof_of_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'proof_of_delivery', 'shipments', ['shipment_id'], ['id'])
    op.alter_column('quality_inspections', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_inspection_number'), 'quality_inspections', type_='unique')
    op.create_index(op.f('ix_quality_inspections_inspection_number'), 'quality_inspections', ['inspection_number'], unique=False)
    op.drop_constraint(op.f('quality_inspections_work_order_id_fkey'), 'quality_inspections', type_='foreignkey')
    op.drop_constraint(op.f('quality_inspections_item_id_fkey'), 'quality_inspections', type_='foreignkey')
    op.create_foreign_key(None, 'quality_inspections', 'inventory_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'quality_inspections', 'work_orders', ['work_order_id'], ['id'])
    op.alter_column('reliability_metrics', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reliability_metrics', 'mtbf_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('reliability_metrics', 'mttr_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('reliability_metrics', 'availability_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('reliability_metrics', 'failures_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reliability_metrics', 'total_runtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('reliability_metrics_asset_id_fkey'), 'reliability_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'reliability_metrics', 'maintenance_assets', ['asset_id'], ['id'])
    op.alter_column('reverse_logistics', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('routing_master', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('routing_master', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_routing_code'), 'routing_master', type_='unique')
    op.create_index(op.f('ix_routing_master_code'), 'routing_master', ['code'], unique=False)
    op.drop_constraint(op.f('routing_master_item_id_fkey'), 'routing_master', type_='foreignkey')
    op.create_foreign_key(None, 'routing_master', 'inventory_items', ['item_id'], ['id'])
    op.alter_column('routing_operations', 'standard_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('routing_operations', 'setup_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('routing_operations', 'labor_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('routing_operations', 'is_inspection_point',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('routing_operations', 'output_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('routing_operations_routing_id_fkey'), 'routing_operations', type_='foreignkey')
    op.drop_constraint(op.f('routing_operations_machine_id_fkey'), 'routing_operations', type_='foreignkey')
    op.drop_constraint(op.f('routing_operations_work_center_id_fkey'), 'routing_operations', type_='foreignkey')
    op.create_foreign_key(None, 'routing_operations', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'routing_operations', 'routing_master', ['routing_id'], ['id'])
    op.create_foreign_key(None, 'routing_operations', 'work_centers', ['work_center_id'], ['id'])
    op.alter_column('scrap_records', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_scrap_number'), 'scrap_records', type_='unique')
    op.create_index(op.f('ix_scrap_records_scrap_number'), 'scrap_records', ['scrap_number'], unique=False)
    op.drop_constraint(op.f('scrap_records_item_id_fkey'), 'scrap_records', type_='foreignkey')
    op.drop_constraint(op.f('scrap_records_work_order_id_fkey'), 'scrap_records', type_='foreignkey')
    op.create_foreign_key(None, 'scrap_records', 'work_orders', ['work_order_id'], ['id'])
    op.create_foreign_key(None, 'scrap_records', 'inventory_items', ['item_id'], ['id'])
    op.drop_constraint(op.f('shipment_items_shipment_id_fkey'), 'shipment_items', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_items', 'shipments', ['shipment_id'], ['id'])
    op.alter_column('shipments', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spare_parts_consumption', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('spare_parts_consumption_work_order_id_fkey'), 'spare_parts_consumption', type_='foreignkey')
    op.drop_constraint(op.f('spare_parts_consumption_item_id_fkey'), 'spare_parts_consumption', type_='foreignkey')
    op.create_foreign_key(None, 'spare_parts_consumption', 'inventory_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'spare_parts_consumption', 'maintenance_work_orders', ['work_order_id'], ['id'])
    op.alter_column('supply_chain_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('supply_chain_timelines', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('supply_chain_timelines_shipment_id_fkey'), 'supply_chain_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'supply_chain_timelines', 'shipments', ['shipment_id'], ['id'])
    op.alter_column('technician_assignments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('warehouses', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'warehouses', 'warehouses', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('work_centers', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_centers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_work_center_code'), 'work_centers', type_='unique')
    op.create_index(op.f('ix_work_centers_code'), 'work_centers', ['code'], unique=False)
    op.alter_column('work_in_progress', 'current_operation_seq',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('work_in_progress', 'quantity_completed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_in_progress', 'material_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_in_progress', 'labor_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_in_progress', 'machine_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('work_in_progress_work_order_id_fkey'), 'work_in_progress', type_='foreignkey')
    op.create_foreign_key(None, 'work_in_progress', 'work_orders', ['work_order_id'], ['id'])
    op.alter_column('work_orders', 'produced_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_orders', 'scrap_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tenant_work_order_number'), 'work_orders', type_='unique')
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=False)
    op.drop_constraint(op.f('work_orders_bom_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_work_center_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_routing_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_machine_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_production_order_id_fkey'), 'work_orders', type_='foreignkey')
    op.create_foreign_key(None, 'work_orders', 'work_centers', ['work_center_id'], ['id'])
    op.create_foreign_key(None, 'work_orders', 'bill_of_materials', ['bom_id'], ['id'])
    op.create_foreign_key(None, 'work_orders', 'routing_master', ['routing_id'], ['id'])
    op.create_foreign_key(None, 'work_orders', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'work_orders', 'production_orders', ['production_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.create_foreign_key(op.f('work_orders_production_order_id_fkey'), 'work_orders', 'production_orders', ['production_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('work_orders_machine_id_fkey'), 'work_orders', 'machines', ['machine_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('work_orders_routing_id_fkey'), 'work_orders', 'routing_master', ['routing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('work_orders_work_center_id_fkey'), 'work_orders', 'work_centers', ['work_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('work_orders_bom_id_fkey'), 'work_orders', 'bill_of_materials', ['bom_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_work_orders_work_order_number'), table_name='work_orders')
    op.create_unique_constraint(op.f('uq_tenant_work_order_number'), 'work_orders', ['tenant_id', 'work_order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'scrap_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('work_orders', 'produced_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'work_in_progress', type_='foreignkey')
    op.create_foreign_key(op.f('work_in_progress_work_order_id_fkey'), 'work_in_progress', 'work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('work_in_progress', 'machine_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('work_in_progress', 'labor_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('work_in_progress', 'material_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('work_in_progress', 'quantity_completed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('work_in_progress', 'current_operation_seq',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_work_centers_code'), table_name='work_centers')
    op.create_unique_constraint(op.f('uq_tenant_work_center_code'), 'work_centers', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('work_centers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_centers', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'parent_id')
    op.alter_column('technician_assignments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'supply_chain_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('supply_chain_timelines_shipment_id_fkey'), 'supply_chain_timelines', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('supply_chain_timelines', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('supply_chain_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'spare_parts_consumption', type_='foreignkey')
    op.drop_constraint(None, 'spare_parts_consumption', type_='foreignkey')
    op.create_foreign_key(op.f('spare_parts_consumption_item_id_fkey'), 'spare_parts_consumption', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('spare_parts_consumption_work_order_id_fkey'), 'spare_parts_consumption', 'maintenance_work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('spare_parts_consumption', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'shipment_items', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_items_shipment_id_fkey'), 'shipment_items', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'scrap_records', type_='foreignkey')
    op.drop_constraint(None, 'scrap_records', type_='foreignkey')
    op.create_foreign_key(op.f('scrap_records_work_order_id_fkey'), 'scrap_records', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('scrap_records_item_id_fkey'), 'scrap_records', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_scrap_records_scrap_number'), table_name='scrap_records')
    op.create_unique_constraint(op.f('uq_tenant_scrap_number'), 'scrap_records', ['tenant_id', 'scrap_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('scrap_records', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'routing_operations', type_='foreignkey')
    op.drop_constraint(None, 'routing_operations', type_='foreignkey')
    op.drop_constraint(None, 'routing_operations', type_='foreignkey')
    op.create_foreign_key(op.f('routing_operations_work_center_id_fkey'), 'routing_operations', 'work_centers', ['work_center_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('routing_operations_machine_id_fkey'), 'routing_operations', 'machines', ['machine_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('routing_operations_routing_id_fkey'), 'routing_operations', 'routing_master', ['routing_id'], ['id'], ondelete='CASCADE')
    op.alter_column('routing_operations', 'output_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('routing_operations', 'is_inspection_point',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('routing_operations', 'labor_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('routing_operations', 'setup_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('routing_operations', 'standard_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'routing_master', type_='foreignkey')
    op.create_foreign_key(op.f('routing_master_item_id_fkey'), 'routing_master', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_routing_master_code'), table_name='routing_master')
    op.create_unique_constraint(op.f('uq_tenant_routing_code'), 'routing_master', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('routing_master', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('routing_master', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reverse_logistics', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'reliability_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('reliability_metrics_asset_id_fkey'), 'reliability_metrics', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reliability_metrics', 'total_runtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('reliability_metrics', 'failures_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reliability_metrics', 'availability_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('reliability_metrics', 'mttr_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('reliability_metrics', 'mtbf_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('reliability_metrics', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'quality_inspections', type_='foreignkey')
    op.drop_constraint(None, 'quality_inspections', type_='foreignkey')
    op.create_foreign_key(op.f('quality_inspections_item_id_fkey'), 'quality_inspections', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quality_inspections_work_order_id_fkey'), 'quality_inspections', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_quality_inspections_inspection_number'), table_name='quality_inspections')
    op.create_unique_constraint(op.f('uq_tenant_inspection_number'), 'quality_inspections', ['tenant_id', 'inspection_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('quality_inspections', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'proof_of_delivery', type_='foreignkey')
    op.create_foreign_key(op.f('proof_of_delivery_shipment_id_fkey'), 'proof_of_delivery', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('proof_of_delivery', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'production_output', type_='foreignkey')
    op.drop_constraint(None, 'production_output', type_='foreignkey')
    op.create_foreign_key(op.f('production_output_item_id_fkey'), 'production_output', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('production_output_work_order_id_fkey'), 'production_output', 'work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('production_output', 'rejected_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_output', 'scrap_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.create_foreign_key(op.f('production_orders_work_center_id_fkey'), 'production_orders', 'work_centers', ['work_center_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('production_orders_bom_id_fkey'), 'production_orders', 'bill_of_materials', ['bom_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('production_orders_plant_id_fkey'), 'production_orders', 'manufacturing_plants', ['plant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('production_orders_item_id_fkey'), 'production_orders', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('production_orders_routing_id_fkey'), 'production_orders', 'routing_master', ['routing_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.create_unique_constraint(op.f('uq_tenant_production_order_number'), 'production_orders', ['tenant_id', 'order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('production_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'production_calendars', type_='foreignkey')
    op.create_foreign_key(op.f('production_calendars_plant_id_fkey'), 'production_calendars', 'manufacturing_plants', ['plant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('production_calendars', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'production_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('production_analytics_plant_id_fkey'), 'production_analytics', 'manufacturing_plants', ['plant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('production_analytics', 'labor_productivity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_analytics', 'throughput_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_analytics', 'scrap_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_analytics', 'yield_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_analytics', 'daily_production_volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_analytics', 'daily_demand',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('production_analytics', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'predictive_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('predictive_alerts_asset_id_fkey'), 'predictive_alerts', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('predictive_alerts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('predictive_alerts', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictive_alerts', 'remaining_useful_life_days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictive_alerts', 'failure_probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('predictive_alerts', 'alert_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'non_conformance_reports', type_='foreignkey')
    op.create_foreign_key(op.f('non_conformance_reports_inspection_id_fkey'), 'non_conformance_reports', 'quality_inspections', ['inspection_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_non_conformance_reports_ncr_number'), table_name='non_conformance_reports')
    op.create_unique_constraint(op.f('uq_tenant_ncr_number'), 'non_conformance_reports', ['tenant_id', 'ncr_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('non_conformance_reports', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'material_consumption', type_='foreignkey')
    op.drop_constraint(None, 'material_consumption', type_='foreignkey')
    op.create_foreign_key(op.f('material_consumption_work_order_id_fkey'), 'material_consumption', 'work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('material_consumption_item_id_fkey'), 'material_consumption', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('material_consumption', 'waste_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'manufacturing_timelines', type_='foreignkey')
    op.drop_constraint(None, 'manufacturing_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('manufacturing_timelines_work_order_id_fkey'), 'manufacturing_timelines', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('manufacturing_timelines_production_order_id_fkey'), 'manufacturing_timelines', 'production_orders', ['production_order_id'], ['id'], ondelete='SET NULL')
    op.alter_column('manufacturing_timelines', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_manufacturing_plants_code'), table_name='manufacturing_plants')
    op.create_unique_constraint(op.f('uq_tenant_plant_code'), 'manufacturing_plants', ['tenant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('manufacturing_plants', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_work_orders', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_work_orders', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_work_orders', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_work_orders_asset_id_fkey'), 'maintenance_work_orders', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('maintenance_work_orders_request_id_fkey'), 'maintenance_work_orders', 'maintenance_requests', ['request_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('maintenance_work_orders_plan_id_fkey'), 'maintenance_work_orders', 'maintenance_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.alter_column('maintenance_work_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maintenance_work_orders', 'estimated_labor_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_work_orders', 'maintenance_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_timelines', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_timelines_work_order_id_fkey'), 'maintenance_timelines', 'maintenance_work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('maintenance_timelines_request_id_fkey'), 'maintenance_timelines', 'maintenance_requests', ['request_id'], ['id'], ondelete='SET NULL')
    op.alter_column('maintenance_timelines', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_requests_asset_id_fkey'), 'maintenance_requests', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maintenance_requests', 'requested_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('maintenance_requests', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_plans', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_plans_asset_id_fkey'), 'maintenance_plans', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_plans', 'estimated_duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_plans', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maintenance_plans', 'maintenance_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_inspections', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_inspections', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_inspections_asset_id_fkey'), 'maintenance_inspections', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('maintenance_inspections_work_order_id_fkey'), 'maintenance_inspections', 'maintenance_work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')
    op.alter_column('maintenance_inspections', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_history', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_history_asset_id_fkey'), 'maintenance_history', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_history', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_history', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_costs', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_costs_work_order_id_fkey'), 'maintenance_costs', 'maintenance_work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_costs', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_costs', 'downtime_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_costs', 'parts_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_costs', 'labor_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'maintenance_calendar', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_calendar', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_calendar_plan_id_fkey'), 'maintenance_calendar', 'maintenance_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('maintenance_calendar_asset_id_fkey'), 'maintenance_calendar', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maintenance_calendar', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_assets', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_assets_plant_id_fkey'), 'maintenance_assets', 'manufacturing_plants', ['plant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('maintenance_assets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maintenance_assets', 'installation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('maintenance_assets', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_analytics_plant_id_fkey'), 'maintenance_analytics', 'manufacturing_plants', ['plant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('maintenance_analytics', 'labor_hours_logged',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_analytics', 'total_maintenance_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_analytics', 'breakdowns_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('maintenance_analytics', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_machines_machine_code'), table_name='machines')
    op.create_unique_constraint(op.f('uq_tenant_machine_code'), 'machines', ['tenant_id', 'machine_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('machines', 'utilization_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('machines', 'calibration_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('machines', 'installation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'machine_performance', type_='foreignkey')
    op.create_foreign_key(op.f('machine_performance_machine_id_fkey'), 'machine_performance', 'machines', ['machine_id'], ['id'], ondelete='CASCADE')
    op.alter_column('machine_performance', 'oee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'quality_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'performance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'availability_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'maintenance_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'idle_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'downtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'runtime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('machine_performance', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('inspection_checklists', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('gps_tracking', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'freight_costs', type_='foreignkey')
    op.create_foreign_key(op.f('freight_costs_shipment_id_fkey'), 'freight_costs', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fleet_vehicles', 'maintenance_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fleet_vehicles', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'availability_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'dispatch_orders', type_='foreignkey')
    op.create_foreign_key(op.f('dispatch_orders_shipment_id_fkey'), 'dispatch_orders', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dispatch_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'delivery_routes', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_routes_shipment_id_fkey'), 'delivery_routes', 'shipments', ['shipment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('delivery_routes', 'optimized',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('carriers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'bom_components', type_='foreignkey')
    op.drop_constraint(None, 'bom_components', type_='foreignkey')
    op.create_foreign_key(op.f('bom_components_bom_id_fkey'), 'bom_components', 'bill_of_materials', ['bom_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bom_components_item_id_fkey'), 'bom_components', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bom_components', 'uom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'bill_of_materials', type_='foreignkey')
    op.create_foreign_key(op.f('bill_of_materials_item_id_fkey'), 'bill_of_materials', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bill_of_materials_bom_number'), table_name='bill_of_materials')
    op.create_unique_constraint(op.f('uq_tenant_bom_number'), 'bill_of_materials', ['tenant_id', 'bom_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('bill_of_materials', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bill_of_materials', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bill_of_materials', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'asset_hierarchy', type_='foreignkey')
    op.drop_constraint(None, 'asset_hierarchy', type_='foreignkey')
    op.create_foreign_key(op.f('asset_hierarchy_parent_asset_id_fkey'), 'asset_hierarchy', 'maintenance_assets', ['parent_asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('asset_hierarchy_child_asset_id_fkey'), 'asset_hierarchy', 'maintenance_assets', ['child_asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('asset_hierarchy', 'relation_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'asset_health', type_='foreignkey')
    op.create_foreign_key(op.f('asset_health_asset_id_fkey'), 'asset_health', 'maintenance_assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.alter_column('asset_health', 'power_consumption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'vibration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'downtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'runtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'operating_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'health_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_health', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_serial_asset_assignments_tenant_id'), table_name='serial_asset_assignments')
    op.drop_index(op.f('ix_serial_asset_assignments_id'), table_name='serial_asset_assignments')
    op.drop_table('serial_asset_assignments')
    op.drop_index(op.f('ix_inventory_quality_inspections_tenant_id'), table_name='inventory_quality_inspections')
    op.drop_index(op.f('ix_inventory_quality_inspections_id'), table_name='inventory_quality_inspections')
    op.drop_table('inventory_quality_inspections')
    op.drop_index(op.f('ix_stock_reservations_tenant_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_id'), table_name='stock_reservations')
    op.drop_table('stock_reservations')
    op.drop_index(op.f('ix_landed_cost_items_tenant_id'), table_name='landed_cost_items')
    op.drop_index(op.f('ix_landed_cost_items_id'), table_name='landed_cost_items')
    op.drop_table('landed_cost_items')
    op.drop_index(op.f('ix_landed_cost_vouchers_tenant_id'), table_name='landed_cost_vouchers')
    op.drop_index(op.f('ix_landed_cost_vouchers_id'), table_name='landed_cost_vouchers')
    op.drop_table('landed_cost_vouchers')
    # ### end Alembic commands ###
