"""add_inventory_suppliers_and_po

Revision ID: da9095f76aa7
Revises: 84f96c264093
Create Date: 2026-07-16 15:18:02.598704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9095f76aa7'
down_revision: Union[str, Sequence[str], None] = '84f96c264093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_suppliers',
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('supplier_code', sa.String(), nullable=False),
    sa.Column('gst', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_suppliers_id'), 'inventory_suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_suppliers_supplier_code'), 'inventory_suppliers', ['supplier_code'], unique=True)
    op.create_index(op.f('ix_inventory_suppliers_tenant_id'), 'inventory_suppliers', ['tenant_id'], unique=False)
    op.create_table('inventory_purchase_orders',
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_purchase_orders_id'), 'inventory_purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_purchase_orders_po_number'), 'inventory_purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_inventory_purchase_orders_tenant_id'), 'inventory_purchase_orders', ['tenant_id'], unique=False)
    op.create_table('inventory_goods_receipts',
    sa.Column('grn_number', sa.String(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['inventory_purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_goods_receipts_grn_number'), 'inventory_goods_receipts', ['grn_number'], unique=True)
    op.create_index(op.f('ix_inventory_goods_receipts_id'), 'inventory_goods_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_goods_receipts_tenant_id'), 'inventory_goods_receipts', ['tenant_id'], unique=False)
    op.create_table('inventory_purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['inventory_purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_purchase_order_items_id'), 'inventory_purchase_order_items', ['id'], unique=False)
    op.drop_constraint(op.f('warehouses_parent_id_fkey'), 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('warehouses_parent_id_fkey'), 'warehouses', 'warehouses', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_inventory_purchase_order_items_id'), table_name='inventory_purchase_order_items')
    op.drop_table('inventory_purchase_order_items')
    op.drop_index(op.f('ix_inventory_goods_receipts_tenant_id'), table_name='inventory_goods_receipts')
    op.drop_index(op.f('ix_inventory_goods_receipts_id'), table_name='inventory_goods_receipts')
    op.drop_index(op.f('ix_inventory_goods_receipts_grn_number'), table_name='inventory_goods_receipts')
    op.drop_table('inventory_goods_receipts')
    op.drop_index(op.f('ix_inventory_purchase_orders_tenant_id'), table_name='inventory_purchase_orders')
    op.drop_index(op.f('ix_inventory_purchase_orders_po_number'), table_name='inventory_purchase_orders')
    op.drop_index(op.f('ix_inventory_purchase_orders_id'), table_name='inventory_purchase_orders')
    op.drop_table('inventory_purchase_orders')
    op.drop_index(op.f('ix_inventory_suppliers_tenant_id'), table_name='inventory_suppliers')
    op.drop_index(op.f('ix_inventory_suppliers_supplier_code'), table_name='inventory_suppliers')
    op.drop_index(op.f('ix_inventory_suppliers_id'), table_name='inventory_suppliers')
    op.drop_table('inventory_suppliers')
    # ### end Alembic commands ###
