"""add_bi_analytics_tables

Revision ID: dc887b9ebdc7
Revises: d0bee58ce072
Create Date: 2026-07-16 18:54:48.696267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc887b9ebdc7'
down_revision: Union[str, Sequence[str], None] = 'd0bee58ce072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bi_alert_rules',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kpi_name', sa.String(), nullable=False),
    sa.Column('condition_operator', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_alert_rules_id'), 'bi_alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_bi_alert_rules_tenant_id'), 'bi_alert_rules', ['tenant_id'], unique=False)
    op.create_table('bi_dashboards',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('role_restrictions', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_dashboards_id'), 'bi_dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_bi_dashboards_tenant_id'), 'bi_dashboards', ['tenant_id'], unique=False)
    op.create_table('bi_reports',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_reports_id'), 'bi_reports', ['id'], unique=False)
    op.create_index(op.f('ix_bi_reports_tenant_id'), 'bi_reports', ['tenant_id'], unique=False)
    op.create_table('bi_alert_logs',
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['bi_alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_alert_logs_alert_rule_id'), 'bi_alert_logs', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_bi_alert_logs_id'), 'bi_alert_logs', ['id'], unique=False)
    op.create_table('bi_dashboard_widgets',
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('size_x', sa.Integer(), nullable=False),
    sa.Column('size_y', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('query_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['bi_dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_dashboard_widgets_dashboard_id'), 'bi_dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_bi_dashboard_widgets_id'), 'bi_dashboard_widgets', ['id'], unique=False)
    op.create_table('bi_scheduled_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('delivery_channel', sa.String(), nullable=False),
    sa.Column('delivery_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['bi_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_scheduled_reports_id'), 'bi_scheduled_reports', ['id'], unique=False)
    op.create_index(op.f('ix_bi_scheduled_reports_report_id'), 'bi_scheduled_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_bi_scheduled_reports_tenant_id'), 'bi_scheduled_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bi_scheduled_reports_tenant_id'), table_name='bi_scheduled_reports')
    op.drop_index(op.f('ix_bi_scheduled_reports_report_id'), table_name='bi_scheduled_reports')
    op.drop_index(op.f('ix_bi_scheduled_reports_id'), table_name='bi_scheduled_reports')
    op.drop_table('bi_scheduled_reports')
    op.drop_index(op.f('ix_bi_dashboard_widgets_id'), table_name='bi_dashboard_widgets')
    op.drop_index(op.f('ix_bi_dashboard_widgets_dashboard_id'), table_name='bi_dashboard_widgets')
    op.drop_table('bi_dashboard_widgets')
    op.drop_index(op.f('ix_bi_alert_logs_id'), table_name='bi_alert_logs')
    op.drop_index(op.f('ix_bi_alert_logs_alert_rule_id'), table_name='bi_alert_logs')
    op.drop_table('bi_alert_logs')
    op.drop_index(op.f('ix_bi_reports_tenant_id'), table_name='bi_reports')
    op.drop_index(op.f('ix_bi_reports_id'), table_name='bi_reports')
    op.drop_table('bi_reports')
    op.drop_index(op.f('ix_bi_dashboards_tenant_id'), table_name='bi_dashboards')
    op.drop_index(op.f('ix_bi_dashboards_id'), table_name='bi_dashboards')
    op.drop_table('bi_dashboards')
    op.drop_index(op.f('ix_bi_alert_rules_tenant_id'), table_name='bi_alert_rules')
    op.drop_index(op.f('ix_bi_alert_rules_id'), table_name='bi_alert_rules')
    op.drop_table('bi_alert_rules')
    # ### end Alembic commands ###
