"""upgrade_scm_module

Revision ID: e8d7f767e098
Revises: d3ab6502c05c
Create Date: 2026-07-16 11:06:17.804625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d7f767e098'
down_revision: Union[str, Sequence[str], None] = 'd3ab6502c05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_rates',
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('origin_zone', sa.String(), nullable=False),
    sa.Column('destination_zone', sa.String(), nullable=False),
    sa.Column('rate_per_km', sa.Float(), nullable=False),
    sa.Column('rate_per_kg', sa.Float(), nullable=False),
    sa.Column('base_charge', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_rates_id'), 'carrier_rates', ['id'], unique=False)
    op.create_index(op.f('ix_carrier_rates_tenant_id'), 'carrier_rates', ['tenant_id'], unique=False)
    op.create_table('container_loading_plans',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=False),
    sa.Column('packing_instructions', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_loading_plans_id'), 'container_loading_plans', ['id'], unique=False)
    op.create_index(op.f('ix_container_loading_plans_tenant_id'), 'container_loading_plans', ['tenant_id'], unique=False)
    op.create_table('scm_delay_alerts',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('delay_type', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scm_delay_alerts_id'), 'scm_delay_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_scm_delay_alerts_tenant_id'), 'scm_delay_alerts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scm_delay_alerts_tenant_id'), table_name='scm_delay_alerts')
    op.drop_index(op.f('ix_scm_delay_alerts_id'), table_name='scm_delay_alerts')
    op.drop_table('scm_delay_alerts')
    op.drop_index(op.f('ix_container_loading_plans_tenant_id'), table_name='container_loading_plans')
    op.drop_index(op.f('ix_container_loading_plans_id'), table_name='container_loading_plans')
    op.drop_table('container_loading_plans')
    op.drop_index(op.f('ix_carrier_rates_tenant_id'), table_name='carrier_rates')
    op.drop_index(op.f('ix_carrier_rates_id'), table_name='carrier_rates')
    op.drop_table('carrier_rates')
    # ### end Alembic commands ###
