"""create_attendance_extended_tables

Revision ID: fcebfa6edd7b
Revises: 7b99d68f2a47
Create Date: 2026-07-10 16:20:03.047232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcebfa6edd7b'
down_revision: Union[str, Sequence[str], None] = '7b99d68f2a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('break_duration', sa.Integer(), nullable=False),
    sa.Column('grace_period', sa.Integer(), nullable=False),
    sa.Column('min_working_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_shift_code')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_tenant_id'), 'shifts', ['tenant_id'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_assignments_effective_date'), 'shift_assignments', ['effective_date'], unique=False)
    op.create_index(op.f('ix_shift_assignments_employee_id'), 'shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_id'), 'shift_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_shift_id'), 'shift_assignments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_tenant_id'), 'shift_assignments', ['tenant_id'], unique=False)
    op.create_table('attendance_breaks',
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('break_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_breaks_attendance_record_id'), 'attendance_breaks', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_breaks_id'), 'attendance_breaks', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_breaks_tenant_id'), 'attendance_breaks', ['tenant_id'], unique=False)
    op.create_table('attendance_regularizations',
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('requested_check_in', sa.String(), nullable=True),
    sa.Column('requested_check_out', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_regularizations_attendance_record_id'), 'attendance_regularizations', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_regularizations_id'), 'attendance_regularizations', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_regularizations_tenant_id'), 'attendance_regularizations', ['tenant_id'], unique=False)
    op.create_table('attendance_timelines',
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_timelines_attendance_record_id'), 'attendance_timelines', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_timelines_id'), 'attendance_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_timelines_tenant_id'), 'attendance_timelines', ['tenant_id'], unique=False)
    op.create_table('overtime_requests',
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('ot_hours', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_requests_attendance_record_id'), 'overtime_requests', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_overtime_requests_id'), 'overtime_requests', ['id'], unique=False)
    op.create_index(op.f('ix_overtime_requests_tenant_id'), 'overtime_requests', ['tenant_id'], unique=False)
    op.add_column('attendance_records', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.add_column('attendance_records', sa.Column('working_hours', sa.Float(), nullable=False))
    op.add_column('attendance_records', sa.Column('ot_hours', sa.Float(), nullable=False))
    op.add_column('attendance_records', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('attendance_records', sa.Column('geofence_status', sa.String(), nullable=False))
    op.add_column('attendance_records', sa.Column('notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'attendance_records', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_column('attendance_records', 'notes')
    op.drop_column('attendance_records', 'geofence_status')
    op.drop_column('attendance_records', 'is_locked')
    op.drop_column('attendance_records', 'ot_hours')
    op.drop_column('attendance_records', 'working_hours')
    op.drop_column('attendance_records', 'shift_id')
    op.drop_index(op.f('ix_overtime_requests_tenant_id'), table_name='overtime_requests')
    op.drop_index(op.f('ix_overtime_requests_id'), table_name='overtime_requests')
    op.drop_index(op.f('ix_overtime_requests_attendance_record_id'), table_name='overtime_requests')
    op.drop_table('overtime_requests')
    op.drop_index(op.f('ix_attendance_timelines_tenant_id'), table_name='attendance_timelines')
    op.drop_index(op.f('ix_attendance_timelines_id'), table_name='attendance_timelines')
    op.drop_index(op.f('ix_attendance_timelines_attendance_record_id'), table_name='attendance_timelines')
    op.drop_table('attendance_timelines')
    op.drop_index(op.f('ix_attendance_regularizations_tenant_id'), table_name='attendance_regularizations')
    op.drop_index(op.f('ix_attendance_regularizations_id'), table_name='attendance_regularizations')
    op.drop_index(op.f('ix_attendance_regularizations_attendance_record_id'), table_name='attendance_regularizations')
    op.drop_table('attendance_regularizations')
    op.drop_index(op.f('ix_attendance_breaks_tenant_id'), table_name='attendance_breaks')
    op.drop_index(op.f('ix_attendance_breaks_id'), table_name='attendance_breaks')
    op.drop_index(op.f('ix_attendance_breaks_attendance_record_id'), table_name='attendance_breaks')
    op.drop_table('attendance_breaks')
    op.drop_index(op.f('ix_shift_assignments_tenant_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_shift_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_employee_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_effective_date'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_shifts_tenant_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
